version: "3.7"
services:
  backend:
    container_name: ATP_Back
    build:
      context: Back-End
      target: build
    restart: always
    ports:
      - 49173:4500
    volumes:
      - ./Back-End/:/code/src:ro
      - ./Back-End/package.json:/code/package.json
      - ./Back-End/package-lock.json:/code/package-lock.json
      - ./Back-End/healthcheck.js:/code/healthcheck.js
    labels:
      - traefik.http.routers.ATP_Back.rule=Host(`api.atypikhouse.art`)
      - traefik.http.routers.ATP_Back.tls=true
      - traefik.http.routers.ATP_Back.tls.certresolver=https_certs
    depends_on:
      - db
  db:
    container_name: ATP_BDD
    image: postgres:12.1
    ports:
      - 49174:5432
    environment:
      POSTGRES_USER: atplead
      POSTGRES_PASSWORD: atprnl
      POSTGRES_DB: AtypikHouse
    restart: always
    volumes:
      - db-data:/var/lib/postgres
  frontend:
    container_name: ATP_Front
    build:
      context: Frontend
    ports:
      - 49176:80
    volumes:
      - ./Frontend:/project
      - ./Frontend/package.json:/project/package.json
      - ./Frontend/package-lock.json:/project/package-lock.json
    labels:
      - traefik.http.routers.ATP_Front.entrypoints=https
      - traefik.http.routers.ATP_Front.rule=Host(`atypikhouse.art`)
      - traefik.http.routers.ATP_Front.tls=true
      - traefik.http.routers.ATP_Front.tls.certresolver=https_certs
    depends_on:
      - backend
volumes:
  db-data:
