version: "3.7"
services:
  backend:
    container_name: ATP_Back
    build:
      context: Back-End
      target: build
    restart: always
    ports:
      - 49173:4500
    volumes:
      - ./Back-End/:/code/src:ro
      - ./Back-End/package.json:/code/package.json
      - ./Back-End/package-lock.json:/code/package-lock.json
    networks:
      - ATP-Front
      - ATP-Back
    depends_on:
      - db
  db:
    container_name: ATP_BDD
    image: postgres:12.1
    ports:
      - 49174:5432
    environment:
      POSTGRES_USER: atplead
      POSTGRES_PASSWORD: atprnl
      POSTGRES_DB: AtypikHouse
    restart: always
    volumes:
      - db-data:/var/lib/postgres
    networks:
      - ATP-Back
  frontend:
    container_name: ATP_Front
    build:
      context: Frontend
    ports:
      - 4200:80
    volumes:
      - ./Frontend:/project
      - ./Frontend/package.json:/project/package.json
      - ./Frontend/package-lock.json:/project/package-lock.json
    labels:
      - traefik.http.routers.blog.rule=Host(`atypikhouse.art`)
#      - traefik.http.routers.blog.tls=true
#      - traefik.http.routers.blog.tls.certresolver=myresolver
    networks:
      - ATP-Front
    depends_on:
      - backend
networks:
  ATP-Front:
  ATP-Back:
volumes:
  db-data:
